server:
    port: 8082

spring:
    application:
        name: policy-service
    jpa:
        database: POSTGRESQL
        show-sql: true
        hibernate:
            ddl-auto: none
    datasource:
        url: jdbc:postgresql://localhost:5432/local_1
        username: usuariopruebas
        password: 1234
        driverClassName: org.postgresql.Driver
